package com.example.dietiestates.ui.theme
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import com.example.dietiestates.R


val RobotoMono = FontFamily(
    Font(R.font.robotomono_bold, weight = FontWeight.Bold),
    Font(R.font.robotomono_bolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotomono_extralight, weight = FontWeight.ExtraLight),
    Font(R.font.robotomono_extralightitalic, weight = FontWeight.ExtraLight, style = FontStyle.Italic),
    Font(R.font.robotomono_italic, weight = FontWeight.Normal, style = FontStyle.Italic),
    Font(R.font.robotomono_light, weight = FontWeight.Light),
    Font(R.font.robotomono_lightitalic, weight = FontWeight.Light, style = FontStyle.Italic),
    Font(R.font.robotomono_medium, weight = FontWeight.Medium),
    Font(R.font.robotomono_mediumitalic, weight = FontWeight.Medium, style = FontStyle.Italic),
    Font(R.font.robotomono_regular, weight = FontWeight.Normal),
    Font(R.font.robotomono_semibold, weight = FontWeight.SemiBold),
    Font(R.font.robotomono_semibolditalic, weight = FontWeight.SemiBold, style = FontStyle.Italic),
    Font(R.font.robotomono_thin, weight = FontWeight.Thin),
    Font(R.font.robotomono_thinitalic, weight = FontWeight.Thin, style = FontStyle.Italic)
)

val RobotoSerif = FontFamily(
    Font(R.font.robotoserif_120pt_black, weight = FontWeight.Black),
    Font(R.font.robotoserif_120pt_blackitalic, weight = FontWeight.Black, style = FontStyle.Italic),
    Font(R.font.robotoserif_120pt_bold, weight = FontWeight.Bold),
    Font(R.font.robotoserif_120pt_bolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotoserif_120pt_extrabold, weight = FontWeight.Bold),
    Font(R.font.robotoserif_120pt_extrabolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotoserif_120pt_extralight, weight = FontWeight.ExtraLight),
    Font(R.font.robotoserif_120pt_extralightitalic, weight = FontWeight.ExtraLight, style = FontStyle.Italic),
    Font(R.font.robotoserif_120pt_italic, weight = FontWeight.Normal, style = FontStyle.Italic),
    Font(R.font.robotoserif_120pt_light, weight = FontWeight.Light),
    Font(R.font.robotoserif_120pt_lightitalic, weight = FontWeight.Light, style = FontStyle.Italic),
    Font(R.font.robotoserif_120pt_medium, weight = FontWeight.Medium),
    Font(R.font.robotoserif_120pt_mediumitalic, weight = FontWeight.Medium, style = FontStyle.Italic),
    Font(R.font.robotoserif_120pt_regular, weight = FontWeight.Normal),
    Font(R.font.robotoserif_120pt_semibold, weight = FontWeight.SemiBold),
    Font(R.font.robotoserif_120pt_semibolditalic, weight = FontWeight.SemiBold, style = FontStyle.Italic),
    Font(R.font.robotoserif_120pt_thin, weight = FontWeight.Thin),
    Font(R.font.robotoserif_120pt_thinitalic, weight = FontWeight.Thin, style = FontStyle.Italic),
    Font(R.font.robotoserif_28pt_black, weight = FontWeight.Black),
    Font(R.font.robotoserif_28pt_blackitalic, weight = FontWeight.Black, style = FontStyle.Italic),
    Font(R.font.robotoserif_28pt_bold, weight = FontWeight.Bold),
    Font(R.font.robotoserif_28pt_bolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotoserif_28pt_extrabold, weight = FontWeight.Bold),
    Font(R.font.robotoserif_28pt_extrabolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotoserif_28pt_extralight, weight = FontWeight.ExtraLight),
    Font(R.font.robotoserif_28pt_extralightitalic, weight = FontWeight.ExtraLight, style = FontStyle.Italic),
    Font(R.font.robotoserif_28pt_italic, weight = FontWeight.Normal, style = FontStyle.Italic),
    Font(R.font.robotoserif_28pt_light, weight = FontWeight.Light),
    Font(R.font.robotoserif_28pt_lightitalic, weight = FontWeight.Light, style = FontStyle.Italic),
    Font(R.font.robotoserif_28pt_medium, weight = FontWeight.Medium),
    Font(R.font.robotoserif_28pt_mediumitalic, weight = FontWeight.Medium, style = FontStyle.Italic),
    Font(R.font.robotoserif_28pt_regular, weight = FontWeight.Normal),
    Font(R.font.robotoserif_28pt_semibold, weight = FontWeight.SemiBold),
    Font(R.font.robotoserif_28pt_semibolditalic, weight = FontWeight.SemiBold, style = FontStyle.Italic),
    Font(R.font.robotoserif_28pt_thin, weight = FontWeight.Thin),
    Font(R.font.robotoserif_28pt_thinitalic, weight = FontWeight.Thin, style = FontStyle.Italic),
    Font(R.font.robotoserif_36pt_black, weight = FontWeight.Black),
    Font(R.font.robotoserif_36pt_blackitalic, weight = FontWeight.Black, style = FontStyle.Italic),
    Font(R.font.robotoserif_36pt_bold, weight = FontWeight.Bold),
    Font(R.font.robotoserif_36pt_bolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotoserif_36pt_extrabold, weight = FontWeight.Bold),
    Font(R.font.robotoserif_36pt_extrabolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotoserif_36pt_extralight, weight = FontWeight.ExtraLight),
    Font(R.font.robotoserif_36pt_extralightitalic, weight = FontWeight.ExtraLight, style = FontStyle.Italic),
    Font(R.font.robotoserif_36pt_italic, weight = FontWeight.Normal, style = FontStyle.Italic),
    Font(R.font.robotoserif_36pt_light, weight = FontWeight.Light),
    Font(R.font.robotoserif_36pt_lightitalic, weight = FontWeight.Light, style = FontStyle.Italic),
    Font(R.font.robotoserif_36pt_medium, weight = FontWeight.Medium),
    Font(R.font.robotoserif_36pt_mediumitalic, weight = FontWeight.Medium, style = FontStyle.Italic),
    Font(R.font.robotoserif_36pt_regular, weight = FontWeight.Normal),
    Font(R.font.robotoserif_36pt_semibold, weight = FontWeight.SemiBold),
    Font(R.font.robotoserif_36pt_semibolditalic, weight = FontWeight.SemiBold, style = FontStyle.Italic),
    Font(R.font.robotoserif_36pt_thin, weight = FontWeight.Thin),
    Font(R.font.robotoserif_36pt_thinitalic, weight = FontWeight.Thin, style = FontStyle.Italic),
    Font(R.font.robotoserif_72pt_black, weight = FontWeight.Black),
    Font(R.font.robotoserif_72pt_blackitalic, weight = FontWeight.Black, style = FontStyle.Italic),
    Font(R.font.robotoserif_72pt_bold, weight = FontWeight.Bold),
    Font(R.font.robotoserif_72pt_bolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotoserif_72pt_extrabold, weight = FontWeight.Bold),
    Font(R.font.robotoserif_72pt_extrabolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotoserif_72pt_extralight, weight = FontWeight.ExtraLight),
    Font(R.font.robotoserif_72pt_extralightitalic, weight = FontWeight.ExtraLight, style = FontStyle.Italic),
    Font(R.font.robotoserif_72pt_italic, weight = FontWeight.Normal, style = FontStyle.Italic),
    Font(R.font.robotoserif_72pt_light, weight = FontWeight.Light),
    Font(R.font.robotoserif_72pt_lightitalic, weight = FontWeight.Light, style = FontStyle.Italic),
    Font(R.font.robotoserif_72pt_medium, weight = FontWeight.Medium),
    Font(R.font.robotoserif_72pt_mediumitalic, weight = FontWeight.Medium, style = FontStyle.Italic),
    Font(R.font.robotoserif_72pt_regular, weight = FontWeight.Normal),
    Font(R.font.robotoserif_72pt_semibold, weight = FontWeight.SemiBold),
    Font(R.font.robotoserif_72pt_semibolditalic, weight = FontWeight.SemiBold, style = FontStyle.Italic),
    Font(R.font.robotoserif_72pt_thin, weight = FontWeight.Thin),
    Font(R.font.robotoserif_72pt_thinitalic, weight = FontWeight.Thin, style = FontStyle.Italic),
    Font(R.font.robotoserif_black, weight = FontWeight.Black),
    Font(R.font.robotoserif_blackitalic, weight = FontWeight.Black, style = FontStyle.Italic),
    Font(R.font.robotoserif_bold, weight = FontWeight.Bold),
    Font(R.font.robotoserif_bolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotoserif_extrabold, weight = FontWeight.Bold),
    Font(R.font.robotoserif_extrabolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.robotoserif_extralight, weight = FontWeight.ExtraLight),
    Font(R.font.robotoserif_extralightitalic, weight = FontWeight.ExtraLight, style = FontStyle.Italic),
    Font(R.font.robotoserif_italic, weight = FontWeight.Normal, style = FontStyle.Italic),
    Font(R.font.robotoserif_light, weight = FontWeight.Light),
    Font(R.font.robotoserif_lightitalic, weight = FontWeight.Light, style = FontStyle.Italic),
    Font(R.font.robotoserif_medium, weight = FontWeight.Medium),
    Font(R.font.robotoserif_mediumitalic, weight = FontWeight.Medium, style = FontStyle.Italic),
    Font(R.font.robotoserif_regular, weight = FontWeight.Normal),
    Font(R.font.robotoserif_semibold, weight = FontWeight.SemiBold),
    Font(R.font.robotoserif_semibolditalic, weight = FontWeight.SemiBold, style = FontStyle.Italic),
    Font(R.font.robotoserif_thin, weight = FontWeight.Thin),
    Font(R.font.robotoserif_thinitalic, weight = FontWeight.Thin, style = FontStyle.Italic)
)

val RobotoSlab = FontFamily(
    Font(R.font.robotoslab_black, weight = FontWeight.Black),
    Font(R.font.robotoslab_bold, weight = FontWeight.Bold),
    Font(R.font.robotoslab_extrabold, weight = FontWeight.Bold),
    Font(R.font.robotoslab_extralight, weight = FontWeight.ExtraLight),
    Font(R.font.robotoslab_light, weight = FontWeight.Light),
    Font(R.font.robotoslab_medium, weight = FontWeight.Medium),
    Font(R.font.robotoslab_regular, weight = FontWeight.Normal),
    Font(R.font.robotoslab_semibold, weight = FontWeight.SemiBold),
    Font(R.font.robotoslab_thin, weight = FontWeight.Thin)
)

val Roboto = FontFamily(
    Font(R.font.roboto_black, weight = FontWeight.Black),
    Font(R.font.roboto_blackitalic, weight = FontWeight.Black, style = FontStyle.Italic),
    Font(R.font.roboto_bold, weight = FontWeight.Bold),
    Font(R.font.roboto_bolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.roboto_extrabold, weight = FontWeight.Bold),
    Font(R.font.roboto_extrabolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.roboto_extralight, weight = FontWeight.ExtraLight),
    Font(R.font.roboto_extralightitalic, weight = FontWeight.ExtraLight, style = FontStyle.Italic),
    Font(R.font.roboto_italic, weight = FontWeight.Normal, style = FontStyle.Italic),
    Font(R.font.roboto_light, weight = FontWeight.Light),
    Font(R.font.roboto_lightitalic, weight = FontWeight.Light, style = FontStyle.Italic),
    Font(R.font.roboto_medium, weight = FontWeight.Medium),
    Font(R.font.roboto_mediumitalic, weight = FontWeight.Medium, style = FontStyle.Italic),
    Font(R.font.roboto_regular, weight = FontWeight.Normal),
    Font(R.font.roboto_semibold, weight = FontWeight.SemiBold),
    Font(R.font.roboto_semibolditalic, weight = FontWeight.SemiBold, style = FontStyle.Italic),
    Font(R.font.roboto_thin, weight = FontWeight.Thin),
    Font(R.font.roboto_thinitalic, weight = FontWeight.Thin, style = FontStyle.Italic)
)

val RobotoCondensed = FontFamily(
    Font(R.font.roboto_condensed_blackitalic, weight = FontWeight.Black, style = FontStyle.Italic),
    Font(R.font.roboto_condensed_bold, weight = FontWeight.Bold),
    Font(R.font.roboto_condensed_bolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.roboto_condensed_extrabold, weight = FontWeight.Bold),
    Font(R.font.roboto_condensed_extrabolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.roboto_condensed_extralight, weight = FontWeight.ExtraLight),
    Font(R.font.roboto_condensed_extralightitalic, weight = FontWeight.ExtraLight, style = FontStyle.Italic),
    Font(R.font.roboto_condensed_italic, weight = FontWeight.Normal, style = FontStyle.Italic),
    Font(R.font.roboto_condensed_light, weight = FontWeight.Light),
    Font(R.font.roboto_condensed_lightitalic, weight = FontWeight.Light, style = FontStyle.Italic),
    Font(R.font.roboto_condensed_medium, weight = FontWeight.Medium),
    Font(R.font.roboto_condensed_mediumitalic, weight = FontWeight.Medium, style = FontStyle.Italic),
    Font(R.font.roboto_condensed_regular, weight = FontWeight.Normal),
    Font(R.font.roboto_condensed_semibold, weight = FontWeight.SemiBold),
    Font(R.font.roboto_condensed_semibolditalic, weight = FontWeight.SemiBold, style = FontStyle.Italic),
    Font(R.font.roboto_condensed_thin, weight = FontWeight.Thin),
    Font(R.font.roboto_condensed_thinitalic, weight = FontWeight.Thin, style = FontStyle.Italic),
    Font(R.font.roboto_semicondensed_black, weight = FontWeight.Black),
    Font(R.font.roboto_semicondensed_blackitalic, weight = FontWeight.Black, style = FontStyle.Italic),
    Font(R.font.roboto_semicondensed_bold, weight = FontWeight.Bold),
    Font(R.font.roboto_semicondensed_bolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.roboto_semicondensed_extrabold, weight = FontWeight.Bold),
    Font(R.font.roboto_semicondensed_extrabolditalic, weight = FontWeight.Bold, style = FontStyle.Italic),
    Font(R.font.roboto_semicondensed_extralight, weight = FontWeight.ExtraLight),
    Font(R.font.roboto_semicondensed_extralightitalic, weight = FontWeight.ExtraLight, style = FontStyle.Italic),
    Font(R.font.roboto_semicondensed_italic, weight = FontWeight.Normal, style = FontStyle.Italic),
    Font(R.font.roboto_semicondensed_light, weight = FontWeight.Light),
    Font(R.font.roboto_semicondensed_lightitalic, weight = FontWeight.Light, style = FontStyle.Italic),
    Font(R.font.roboto_semicondensed_medium, weight = FontWeight.Medium),
    Font(R.font.roboto_semicondensed_mediumitalic, weight = FontWeight.Medium, style = FontStyle.Italic),
    Font(R.font.roboto_semicondensed_regular, weight = FontWeight.Normal),
    Font(R.font.roboto_semicondensed_semibold, weight = FontWeight.SemiBold),
    Font(R.font.roboto_semicondensed_semibolditalic, weight = FontWeight.SemiBold, style = FontStyle.Italic),
    Font(R.font.roboto_semicondensed_thin, weight = FontWeight.Thin),
    Font(R.font.roboto_semicondensed_thinitalic, weight = FontWeight.Thin, style = FontStyle.Italic)
)
